version: "3.3"

networks:
  etcd:
    external: true

services:

  etcd:
    image: appcelerator/etcd:latest
    networks:
      - etcd
    environment:
      SERVICE_NAME: "etcd"
      MIN_SEEDS_COUNT: 3
    deploy:
      mode: replicated
      replicas: 3
